### ISSUE TITLE
Project Basic flow setup

### ISSUE THREAD

**Issue by umagnanasundaram2128** [nehajaideep/WolfTrack3.0#17]
- [x] Zenodo Badge
- [x] Code Coverage
- [x] Travis (if applicable)
- [x] Git Workflow actions

**Comment by umagnanasundaram2128** [comment]
@nehajaideep What is the status on this task?

**Comment by nehajaideep** [comment]
Working on it. Should be done by tomorrow.

**Comment by umagnanasundaram2128** [comment]
This task is completed and working fine. Hence, closing this issue
Thank you @nehajaideep for working on this.
