### ISSUE TITLE
Add CV not accepting all type of documents

### ISSUE THREAD

**Issue by niveditalodha** [nehajaideep/WolfTrack3.0#2]

**Comment by niveditalodha** [comment]
The add CV is not accepting formats like pdf aur png for resume. It only accepts docx

**Comment by umagnanasundaram2128** [comment]
@nehajaideep can you please take this issue and work on it?

**Comment by niveditalodha** [comment]
@umagnanasundaram2128 Added pdf file parser in cdf933349e3ba3dc7dd0ed537ecfe4c7430ba596. The add cv will now accept pdf file along with docx file. Please check

**Comment by nehajaideep** [comment]
Added image parser in 511d73defcae9d160f4c644162fe69d01863171d. The add cv will now accept jpg, png and jpeg. Please check.

**Comment by umagnanasundaram2128** [comment]
This feature working as expected! Closing this issue. 
Thank you @nehajaideep and @niveditalodha for working on this enhancement.
