### ISSUE TITLE
Render Main Login/Signup page for default application url

### ISSUE THREAD

**Issue by akhilkumarmengani** [nehajaideep/WolfTrack3.0#23]
User should be navigated to main login page to select admin/user login for default url

**Comment by niveditalodha** [comment]
@akhilkumarmengani This issue was fixed in 1fc314fa364f6cfc5edcbda265d7ff0bcf700636

**Comment by umagnanasundaram2128** [comment]
@niveditalodha @akhilkumarmengani I have checked this issue. It is resolved and working fine. Hence, closing this issue.
Thank you @niveditalodha for fixing it. 👍
