### ISSUE TITLE
Scrapper to get jobs with job description related to user resume

### ISSUE THREAD

**Issue by vamshi-chidara** [nehajaideep/WolfTrack3.0#24]
The current implementation only has the algorithm to calculate how related is the resume to the job description the user enters in the text area. The enhancement idea is to 
- Implement a scrapper which would scrape the job postings on the internet
- Suggest related jobs to the user based on his resume

**Comment by niveditalodha** [comment]
@vamshi-chidara Any update?

**Comment by vamshi-chidara** [comment]
I had completed the scrapper and pushed it in this [commit](https://github.com/nehajaideep/WolfTrack2.0/commit/db5b6578be965e932dcf7be4a747b62cdc8aed7a)

**Comment by niveditalodha** [comment]
Great! Time to close it :P
