### ISSUE TITLE
Button name change in the login page

### ISSUE THREAD

**Issue by akhilkumarmengani** [nehajaideep/WolfTrack3.0#29]
Change the button name to sign up and login the login page.
It is currently shown as submit.
![Screen Shot 2021-11-28 at 4 13 44 PM](https://user-images.githubusercontent.com/70975566/143786179-50a15c55-2011-4608-b708-b58a26740ba1.png)

@vamshi-chidara

**Comment by vamshi-chidara** [comment]
I had resolved the issue in this [commit](https://github.com/nehajaideep/WolfTrack3.0/commit/e971f6b0fc835566cedb9db172f189aa60c25bd6). Please check.

**Comment by umagnanasundaram2128** [comment]
@vamshi-chidara This is working fine. Closing the issue.
