### ISSUE TITLE
Move Application Title 'WolfTrack3.0' to the center in the Navigation bar

### ISSUE THREAD

**Issue by akhilkumarmengani** [nehajaideep/WolfTrack3.0#30]
Application Title appears to floating at the left of the navigation bar. It should be moved to the center of the navigation bar.
Please refer to the screenshot attached below.

![Screen Shot 2021-11-28 at 4 59 25 PM](https://user-images.githubusercontent.com/70975566/143787735-3d64e41e-deba-464b-bc82-59a7f2430b08.png)

**Comment by niveditalodha** [comment]
@akhilkumarmengani  issue resolved in f1cafeeee3ce07bee4615c5661ba2c19d7c952e5

**Comment by umagnanasundaram2128** [comment]
This issue is resolved. Closing this issue.
