### ISSUE TITLE
Error messages not showing

### ISSUE THREAD

**Issue by niveditalodha** [nehajaideep/WolfTrack3.0#4]

**Comment by niveditalodha** [comment]
Proper error messages are not shown when user goes to a page which requires additional data. Like view CV before adding CV

**Comment by niveditalodha** [comment]
The unauthorized error which occurs on the home page when not logged in is resolved. @akhilkumarmengani  Please check and close

**Comment by umagnanasundaram2128** [comment]
@niveditalodha The bug is resolved. I am closing this issue.
