### ISSUE TITLE
Send profile should send resume in the mail

### ISSUE THREAD

**Issue by niveditalodha** [nehajaideep/WolfTrack3.0#5]

**Comment by niveditalodha** [comment]
Currently send profile is only sending the job details which are applied and offers received. It should also send the resume of the applicant

**Comment by niveditalodha** [comment]
Added the resume as an attachment in email functionality. Please test and close @akhilkumarmengani

**Comment by umagnanasundaram2128** [comment]
@niveditalodha This feature works great! :-D
