### ISSUE TITLE
Card links in the cards' alignment inconsistent

### ISSUE THREAD

**Issue by umagnanasundaram2128** [nehajaideep/WolfTrack3.0#9]
In each card(Wish list, In process, Applied and completed) we have two links: Add new and view more.
The alignment of the links in all the cards are not consistent.

**Comment by umagnanasundaram2128** [comment]
I am working on this issue.

**Comment by umagnanasundaram2128** [comment]
Fixed this issue please check and close @niveditalodha

**Comment by niveditalodha** [comment]
Issue fixed
